language: node_js

node_js:
  - "8"
  - "6"
  - "5"
  - "4"

before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi

script:
   - grunt standards
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
